### ISSUE TITLE
Cannot send messages after /otr finish

### ISSUE THREAD

**Issue by ProgVal** [mmb/weechat-otr#109]
I get this traceback:

```
11:45 :! otr !: Traceback (most recent call last):
11:45   File "/home/progval/.weechat/python/autoload/otr.py", line 1214, in message_out_cb
11:45     context.msg_convert_out(parsed['text']))
11:45   File "/home/progval/.local/lib/python2.7/site-packages/potr/context.py", line 262, in sendMessage
11:45     msg = bytes(msg)
11:45   File "/home/progval/.local/lib/python2.7/site-packages/potr/proto.py", line 51, in <lambda>
11:45     cls.__str__ = lambda self: self.__bytes__()
11:45   File "/home/progval/.weechat/python/autoload/otr.py", line 190, in patched__bytes__
11:45     for v in self.versions:
11:45 AttributeError: 'TaggedPlaintext' object has no attribute 'versions'
```

**Comment by ProgVal** [comment]
And I could send message again after the other person sent me a message

**Comment by mmb** [comment]
It looks like you might have an older version of pure python otr. Can you confirm the version with:

`python -c 'import potr; print potr.VERSION'`

You might be able to update it with:

`pip install --upgrade --user python-potr`

**Comment by ProgVal** [comment]
That fixed it, thanks.
