### ISSUE TITLE
AttributeError: 'Error' object has no attribute 'decode'

### ISSUE THREAD

**Issue by konomikitten** [mmb/weechat-otr#138]
I got this error on startup of WeeChat, I presume it might be because `to_unicode` was fed a NUL or empty value for `strng`. I can provide additional information if needed.

````
23:48 python: stdout/stderr (otr): Versions: weechat-otr 1.9.2, potr 1.0.0-final, Python 2.7.16+, WeeChat 2.3
23:48 python: stdout/stderr (otr): Traceback (most recent call last):
23:48 python: stdout/stderr (otr):   File "/home/user/.weechat/python/autoload/otr.py", line 1214, in message_in_cb
23:48 python: stdout/stderr (otr):     PYVER.to_unicode(err.args[0])), 'error')
23:48 python: stdout/stderr (otr):   File "/home/user/.weechat/python/autoload/otr.py", line 77, in to_unicode
23:48 python: stdout/stderr (otr):     return strng.decode('utf-8', 'replace')
23:48 python: stdout/stderr (otr): AttributeError: 'Error' object has no attribute 'decode'
23:48 =!= python: error in function "message_in_cb"
23:48 python: stdout/stderr (otr): Versions: weechat-otr 1.9.2, potr 1.0.0-final, Python 2.7.16+, WeeChat 2.3
23:48 python: stdout/stderr (otr): Traceback (most recent call last):
23:48 python: stdout/stderr (otr):   File "/home/user/.weechat/python/autoload/otr.py", line 1214, in message_in_cb
23:48 python: stdout/stderr (otr):     PYVER.to_unicode(err.args[0])), 'error')
23:48 python: stdout/stderr (otr):   File "/home/user/.weechat/python/autoload/otr.py", line 77, in to_unicode
23:48 python: stdout/stderr (otr):     return strng.decode('utf-8', 'replace')
23:48 python: stdout/stderr (otr): AttributeError: 'Error' object has no attribute 'decode'
23:48 =!= python: error in function "message_in_cb"
````

**Comment by konomikitten** [comment]
After looking back over the session it looks like my znc replayed my own log to me so that might be how I ended up with this error. An exception for source and dest nick being the same may be needed?

````
16:55:12 Konomi | ?OTR Error:You sent encrypted data, but I wasn't expecting it.
````
